# This is a config for E2B sandbox template.
# You can use template ID (ptdq4y2y6jburj1tjjff) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("ptdq4y2y6jburj1tjjff") # Sync sandbox
# sandbox = await AsyncSandbox.create("ptdq4y2y6jburj1tjjff") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ptdq4y2y6jburj1tjjff')

team_id = "d8d5e5f8-96d7-4eba-9173-280bc2259420"
dockerfile = "e2b.Dockerfile"
template_id = "ptdq4y2y6jburj1tjjff"
